**<h1>Learning Plotly</h1>**
#### `histogram`, `bar`, `line`

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
# import dataset
df = pd.read_csv("Final Visualization Dataset.csv")

In [3]:
with pd.option_context('display.max_columns',None):
    display(df.sample(5))

,Age,Attrition,Business Travel,Compensation Rate,Department,Distance From Home,Education,Education Field,Environment Satisfaction,Gender,Hourly Rate,Job Involvement,Job Level,Job Role,Job Satisfaction,Marital Status,Monthly Income,Monthly Rate,Num Companies Worked,Over Time,Percent Salary Hike,Performance Rating,Relationship Satisfaction,Stock Option Level,Total Working Years,Training Times Last Year,Work Life Balance,Years At Company,Years In Current Role,Years Since Last Promotion,Years With Curr Manager,Education Labels,Environment Satisfaction Labels,Job Involvement Labels,Job Level Label,Relationship Satisfaction Labels,Avg Tenure Per Company,Candidate Stability,Training Intensity,Work Life Balance Labels,Role Stagnation Index,Promotion Gap Ratio,Manager Stability Indicator,Manager Stability Indicator Labels,Promotion Risk Cluster
129,49,0,Travel_Rarely,470,Research & Development,20,4,Medical,3,Female,96,3,2,Manufacturing Director,1,Married,6567,5549,1,No,14,3,3,0,16,2,2,15,11,5,11,Master,High,Highly Involved,Mid-Level,Satisfied,16.0,High Stability (5+ yrs),0.13,Fair,0.73,0.33,4,Highly Stable,Role-Stagnant Mid-Level
925,42,0,Travel_Rarely,603,Research & Development,7,4,Medical,2,Female,78,4,2,Research Scientist,2,Married,2372,5628,6,Yes,16,3,4,0,18,2,3,1,0,0,0,Master,Medium,Fully Dedicated,Mid-Level,Very Satisfied,3.0,Moderate Stability (2-5 yrs),2.00,Good,0.00,0.00,1,New Relationship,Early-Career Explorers
111,34,1,Travel_Frequently,658,Research & Development,7,3,Life Sciences,1,Male,66,1,2,Laboratory Technician,3,Single,6074,22887,1,Yes,24,4,4,0,9,3,3,9,7,0,6,Bachelor,Low,Minimally Involved,Mid-Level,Very Satisfied,9.0,High Stability (5+ yrs),0.33,Good,0.78,0.00,3,Stable,Fast-Track High Performers
1044,49,0,Travel_Rarely,1495,Research & Development,5,4,Technical Degree,1,Male,96,3,2,Healthcare Representative,3,Married,6651,21534,2,No,14,3,2,1,20,0,2,3,2,1,2,Master,Low,Highly Involved,Mid-Level,Dissatisfied,10.0,High Stability (5+ yrs),0.00,Fair,0.67,0.33,2,Developing,Early-Career Explorers
1261,38,0,Travel_Rarely,833,Research & Development,18,3,Medical,2,Male,60,1,2,Healthcare Representative,4,Married,5811,24539,3,Yes,16,3,3,1,15,2,3,1,0,1,0,Bachelor,Medium,Minimally Involved,Mid-Level,Satisfied,5.0,Moderate Stability (2-5 yrs),2.00,Good,0.00,1.00,1,New Relationship,Early-Career Explorers

---

### **Histogram**

In [4]:
fig = px.histogram(df, x='Education Field', color='Education Field', text_auto=True)        # text position shows the count labels
fig.update_traces(textposition='outside')                                                   # shows the count labels outside of histplots
fig.show()

In [5]:
fig = px.histogram(df, x='Job Role', color='Job Role', text_auto=True, height=600)
fig.update_traces(textposition='outside')
fig.show()

In [6]:
fig = px.histogram(df, x='Education Field', color='Education Field', color_discrete_sequence=['red','blue','black','green','yellow','purple'], text_auto=True)
fig.update_traces(textposition='outside')
fig.show()

In [7]:
df['Education Field'].value_counts().reset_index()

    Education Field  count
0     Life Sciences    606
1           Medical    464
2         Marketing    159
3  Technical Degree    132
4             Other     82
5   Human Resources     27

In [8]:
temp = df['Education Field'].value_counts().reset_index()
px.histogram(temp, x='Education Field', y='count', color='Education Field', text_auto=True)

---

### Using Inbuild Plotly 
### **Barplot**

In [9]:
px.data.gapminder()                         # using Gapminder dataset

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [10]:
df = px.data.gapminder()

In [11]:
with pd.option_context('display.max_rows',None):
    display(df['country'].value_counts())

country
Afghanistan                 12
Pakistan                    12
New Zealand                 12
Nicaragua                   12
Niger                       12
Nigeria                     12
Norway                      12
Oman                        12
Panama                      12
Nepal                       12
Paraguay                    12
Peru                        12
Philippines                 12
Poland                      12
Portugal                    12
Puerto Rico                 12
Netherlands                 12
Namibia                     12
Romania                     12
Mali                        12
Lesotho                     12
Liberia                     12
Libya                       12
Madagascar                  12
Malawi                      12
Malaysia                    12
Mauritania                  12
Myanmar                     12
Mauritius                   12
Mexico                      12
Mongolia                    12
Montenegro                  12
Morocco                     12
Mozambique                  12
Reunion                     12
Rwanda                      12
Albania                     12
United Kingdom              12
Thailand                    12
Togo                        12
Trinidad and Tobago         12
Tunisia                     12
Turkey                      12
Uganda                      12
United States               12
Taiwan                      12
Uruguay                     12
Venezuela                   12
Vietnam                     12
West Bank and Gaza          12
Yemen, Rep.                 12
Zambia                      12
Tanzania                    12
Syria                       12
Sao Tome and Principe       12
Slovenia                    12
Saudi Arabia                12
Senegal                     12
Serbia                      12
Sierra Leone                12
Singapore                   12
Slovak Republic             12
Somalia                     12
Switzerland                 12
South Africa                12
Spain                       12
Sri Lanka                   12
Sudan                       12
Swaziland                   12
Sweden                      12
Lebanon                     12
Kuwait                      12
Korea, Rep.                 12
Comoros                     12
Canada                      12
Central African Republic    12
Chad                        12
Chile                       12
China                       12
Colombia                    12
Congo, Dem. Rep.            12
Cambodia                    12
Congo, Rep.                 12
Costa Rica                  12
Cote d'Ivoire               12
Croatia                     12
Cuba                        12
Czech Republic              12
Cameroon                    12
Burundi                     12
Korea, Dem. Rep.            12
Bangladesh                  12
Algeria                     12
Angola                      12
Argentina                   12
Australia                   12
Austria                     12
Bahrain                     12
Belgium                     12
Burkina Faso                12
Benin                       12
Bolivia                     12
Bosnia and Herzegovina      12
Botswana                    12
Brazil                      12
Bulgaria                    12
Denmark                     12
Djibouti                    12
Dominican Republic          12
Iraq                        12
Hong Kong, China            12
Hungary                     12
Iceland                     12
India                       12
Indonesia                   12
Iran                        12
Ireland                     12
Ecuador                     12
Israel                      12
Italy                       12
Jamaica                     12
Japan                       12
Jordan                      12
Kenya                       12
Honduras                    12
Haiti                       12
Guinea-Bissau               12
Guinea                      12
Guatemala                   12
Greece                      12
Ghana                       12
Germany                     12
Gambia                      12
Gabon                       12
France                      12
Finland                     12
Ethiopia                    12
Eritrea                     12
Equatorial Guinea           12
El Salvador                 12
Egypt                       12
Zimbabwe                    12
Name: count, dtype: int64

In [12]:
canada = df[df['country'] == 'Canada']

In [13]:
canada

    country continent  year  lifeExp       pop    gdpPercap iso_alpha  iso_num
240  Canada  Americas  1952   68.750  14785584  11367.16112       CAN      124
241  Canada  Americas  1957   69.960  17010154  12489.95006       CAN      124
242  Canada  Americas  1962   71.300  18985849  13462.48555       CAN      124
243  Canada  Americas  1967   72.130  20819767  16076.58803       CAN      124
244  Canada  Americas  1972   72.880  22284500  18970.57086       CAN      124
245  Canada  Americas  1977   74.210  23796400  22090.88306       CAN      124
246  Canada  Americas  1982   75.760  25201900  22898.79214       CAN      124
247  Canada  Americas  1987   76.860  26549700  26626.51503       CAN      124
248  Canada  Americas  1992   77.950  28523502  26342.88426       CAN      124
249  Canada  Americas  1997   78.610  30305843  28954.92589       CAN      124
250  Canada  Americas  2002   79.770  31902268  33328.96507       CAN      124
251  Canada  Americas  2007   80.653  33390141  36319.23501       CAN      124

In [14]:
fig = px.bar(canada, x='year',y='pop', width=550, height=600, text='year', color='pop',
        hover_data=['lifeExp', 'gdpPercap','continent','country'],                    # the respected feature data will be displayed when featured over the data
        title='Population of Canada Over the Years',
        color_continuous_scale = ['green','yellow','red']                             # setting the color format from green to yellow to red
)

fig.update_layout(title_x=0.5)                                                        # puts the heading of the plot to the center

In [15]:
fig = px.bar(canada, x='year',y='lifeExp', width=550, height=600, text='year', color='pop',                 
        labels = {'lifeExp':'Life Expectancy',
                'year':'Year',
                'pop':'Population'
                  },                         # changes the names of the features
        title='Population of Canada Over the Years',
        color_continuous_scale = ['green','yellow','red']                          
)

fig.update_layout(title_x=0.5)

In [16]:
# using groupby -- only contains year and gdpPercap
data = df.groupby('year', as_index=False)['gdpPercap'].mean().round(2)


fig = px.bar(data, x='year', y='gdpPercap', text='gdpPercap',
            title='GDP Per Capital Over the Years',
            width=700,
            color='gdpPercap',
            color_continuous_scale=['green','yellow','red']
)
fig.update_layout(title_x=0.5)
fig.show()

### Making new dataset

In [17]:
df = px.data.medals_long()                  # dataset on countries owning the medals

In [18]:
df

        nation   medal  count
0  South Korea    gold     24
1        China    gold     10
2       Canada    gold      9
3  South Korea  silver     13
4        China  silver     15
5       Canada  silver     12
6  South Korea  bronze     11
7        China  bronze      8
8       Canada  bronze     12

In [19]:
px.bar(df, x='nation',y='count',color='medal', width=600,
        color_discrete_map={            # setting different colors to different medal types
            'gold':'red',
            'silver':'green',
            'bronze':'blue'
        },
        text = 'medal'
       )

---

### **Lineplot**

In [20]:
px.data.gapminder()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [ ]:
df = px.data.gapminder().query("country == 'Canada'")               # .query() -- it can also be used with pandas dataframes, coz it is a pandas command

In [23]:
df

    country continent  year  lifeExp       pop    gdpPercap iso_alpha  iso_num
240  Canada  Americas  1952   68.750  14785584  11367.16112       CAN      124
241  Canada  Americas  1957   69.960  17010154  12489.95006       CAN      124
242  Canada  Americas  1962   71.300  18985849  13462.48555       CAN      124
243  Canada  Americas  1967   72.130  20819767  16076.58803       CAN      124
244  Canada  Americas  1972   72.880  22284500  18970.57086       CAN      124
245  Canada  Americas  1977   74.210  23796400  22090.88306       CAN      124
246  Canada  Americas  1982   75.760  25201900  22898.79214       CAN      124
247  Canada  Americas  1987   76.860  26549700  26626.51503       CAN      124
248  Canada  Americas  1992   77.950  28523502  26342.88426       CAN      124
249  Canada  Americas  1997   78.610  30305843  28954.92589       CAN      124
250  Canada  Americas  2002   79.770  31902268  33328.96507       CAN      124
251  Canada  Americas  2007   80.653  33390141  36319.23501       CAN      124

In [30]:
fig = px.line(df, x='year', y='lifeExp', title='Life Expectancy in Canada',
                labels={
                    'lifeExp' : 'Life Expectancy',
                    'year' : 'Year'
                }
              )
fig.update_layout(title_x=0.5)
fig.show()

In [41]:
# checking for countries in each continent

temp = px.data.gapminder()

for i in temp['continent'].unique():
    print(f"{i}  --->  \n{temp[temp['continent'] == i]['country'].unique()}")
    print(f"-------------------------------------------------------------------\n")

Asia  --->
['Afghanistan' 'Bahrain' 'Bangladesh' 'Cambodia' 'China'
 'Hong Kong, China' 'India' 'Indonesia' 'Iran' 'Iraq' 'Israel' 'Japan'
 'Jordan' 'Korea, Dem. Rep.' 'Korea, Rep.' 'Kuwait' 'Lebanon' 'Malaysia'
 'Mongolia' 'Myanmar' 'Nepal' 'Oman' 'Pakistan' 'Philippines'
 'Saudi Arabia' 'Singapore' 'Sri Lanka' 'Syria' 'Taiwan' 'Thailand'
 'Vietnam' 'West Bank and Gaza' 'Yemen, Rep.']
-------------------------------------------------------------------

Europe  --->
['Albania' 'Austria' 'Belgium' 'Bosnia and Herzegovina' 'Bulgaria'
 'Croatia' 'Czech Republic' 'Denmark' 'Finland' 'France' 'Germany'
 'Greece' 'Hungary' 'Iceland' 'Ireland' 'Italy' 'Montenegro' 'Netherlands'
 'Norway' 'Poland' 'Portugal' 'Romania' 'Serbia' 'Slovak Republic'
 'Slovenia' 'Spain' 'Sweden' 'Switzerland' 'Turkey' 'United Kingdom']
-------------------------------------------------------------------

Africa  --->
['Algeria' 'Angola' 'Benin' 'Botswana' 'Burkina Faso' 'Burundi' 'Cameroon'
 'Central African Republic' 'Chad' 'Comoros' 'Congo, Dem. Rep.'
 'Congo, Rep.' "Cote d'Ivoire" 'Djibouti' 'Egypt' 'Equatorial Guinea'
 'Eritrea' 'Ethiopia' 'Gabon' 'Gambia' 'Ghana' 'Guinea' 'Guinea-Bissau'
 'Kenya' 'Lesotho' 'Liberia' 'Libya' 'Madagascar' 'Malawi' 'Mali'
 'Mauritania' 'Mauritius' 'Morocco' 'Mozambique' 'Namibia' 'Niger'
 'Nigeria' 'Reunion' 'Rwanda' 'Sao Tome and Principe' 'Senegal'
 'Sierra Leone' 'Somalia' 'South Africa' 'Sudan' 'Swaziland' 'Tanzania'
 'Togo' 'Tunisia' 'Uganda' 'Zambia' 'Zimbabwe']
-------------------------------------------------------------------

Americas  --->
['Argentina' 'Bolivia' 'Brazil' 'Canada' 'Chile' 'Colombia' 'Costa Rica'
 'Cuba' 'Dominican Republic' 'Ecuador' 'El Salvador' 'Guatemala' 'Haiti'
 'Honduras' 'Jamaica' 'Mexico' 'Nicaragua' 'Panama' 'Paraguay' 'Peru'
 'Puerto Rico' 'Trinidad and Tobago' 'United States' 'Uruguay' 'Venezuela']
-------------------------------------------------------------------

Oceania  --->
['Australia' 'New Zealand']
-------------------------------------------------------------------

In [55]:
fig = px.line(temp[temp['continent'] == 'Oceania'], x='year',y='lifeExp', color='country', markers=True)            # if marker is set to true, then little circular data points will be plotted on the line graph
fig.show()

In [54]:
fig = px.line(temp[temp['continent'] == 'Americas'], x='year',y='lifeExp', color='country')
fig.show()

In [56]:
# USING ANOTHER DATASET
df = px.data.stocks()
df.head()

         date      GOOG      AAPL      AMZN        FB      NFLX      MSFT
0  2018-01-01  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
1  2018-01-08  1.018172  1.011943  1.061881  0.959968  1.053526  1.015988
2  2018-01-15  1.032008  1.019771  1.053240  0.970243  1.049860  1.020524
3  2018-01-22  1.066783  0.980057  1.140676  1.016858  1.307681  1.066561
4  2018-01-29  1.008773  0.917143  1.163374  1.018357  1.273537  1.040708

In [74]:
fig = px.line(df, x='date', y='GOOG', markers=True)

# Tell the x-axis to place a tick mark every 12 Months ("M12")
# Tell it to format the text as a 4-digit Year ("%Y")
fig.update_xaxes(dtick="M12", tickformat="%Y")

fig.show()

In [71]:
fig = px.line(df, x='date', y='GOOG')

# dtick="M1" places a tick mark every 1 Month
# tickformat="%b %Y" formats the text to look like "Jan 2018"
fig.update_xaxes(dtick="M1", tickformat="%b %Y")

fig.show()

In [84]:
# Plotting all the graphs at once
cols = ['GOOG', 'AAPL', 'AMZN', 'FB', 'NFLX', 'MSFT']

fig = px.line(df, x='date', y=cols, title='Tech Stocks Over Time')
fig.update_xaxes(dtick='M1', tickformat="%b %Y")
fig.show()

In [81]:
# Plotting all the graphs one after another
cols = ['GOOG', 'AAPL', 'AMZN', 'FB', 'NFLX', 'MSFT']

for i in cols:
    fig = px.line(df, x='date', y=i, title=i)
    fig.update_xaxes(dtick='M1', tickformat="%b %Y")
    fig.show()