### `histogram`

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [3]:
df = px.data.tips()
df.sample(5)

    total_bill   tip     sex smoker   day    time  size
85       34.83  5.17  Female     No  Thur   Lunch     4
58       11.24  1.76    Male    Yes   Sat  Dinner     2
24       19.82  3.18    Male     No   Sat  Dinner     2
45       18.29  3.00    Male     No   Sun  Dinner     2
86       13.03  2.00    Male     No  Thur   Lunch     2

In [ ]:
fig = px.histogram(df, x='total_bill')
fig.show()

In [20]:
fig = px.histogram(df, x='total_bill', nbins=20)            # putting bins
fig.update_layout(bargap=0.2)                               # puts gap btwn bars
fig.show()

In [10]:
fig = px.histogram(df, x='day')
fig.show()

In [ ]:
# using Histnorm

fig = px.histogram(df, x='total_bill', histnorm=None)          # histnorm changes what y axis of histogram represents
# histnorm takes only 5 values
    # None -- by default takes 'count'
    # percent
    # probability
    # density
    # probability density

fig.show()

In [ ]:
# using Histfunc

fig = px.histogram(df, x='total_bill', y='tip', histfunc='avg')         # make the y axis into avg
# the values histfunc takes
    # count
    # avg
    # sum
    # min
    # max
    
fig.show()

In [16]:
stocks = px.data.stocks()
stocks.sample(5)

          date      GOOG      AAPL      AMZN        FB      NFLX      MSFT
20  2018-05-21  0.975894  1.077600  1.309981  0.989671  1.672889  1.115319
30  2018-07-30  1.110213  1.188514  1.483387  0.951458  1.633840  1.225082
40  2018-10-08  1.007122  1.269200  1.455172  0.822799  1.617029  1.242431
23  2018-06-11  1.045390  1.079086  1.396074  1.048167  1.866660  1.135389
58  2019-02-11  1.010361  0.973829  1.308191  0.869682  1.699462  1.227123

In [22]:
fig = px.histogram(stocks, x='date')
fig.update_layout(bargap=0.2)
fig.show()